### PR TITLE
Add playlist script

### PR DESCRIPTION
**Pull request by viettrung9012**
@icyflame please help review
Regarding issue #1

### CODE REVIEW

**Comment by icyflame** [comment]
Thanks a lot! I was actually leaning towards creating the playlist from the main script itself. That way, the name of the playlist can be decided on the basis of the channels (i.e. `<CHANNEL_NAME> Chronological - <yyyy-mm-dd>`)

It should be easy to refactor your script to return a promise which happens right after we get the IDs of all the channels. i.e. [before this line](https://github.com/icyflame/youtube-chronological/blob/d3c261eacb2243f75c2e98b615b0b4d2910c6ea6/index.js#L34)

I am thinking about code something like:
```js
let createPlaylist = require('./playlist.js');

...
// Line 34
.then (channels => {
    createPlaylist(playlistName).then(response => {
        console.log("New playlist created!");
        let basePlayListId = response.blah;
      
        // 2. Get video IDs for these channels
```

**Comment by viettrung9012** [comment]
Yes, that could be done. I'll update this on weekend

**Comment by icyflame** [comment]
Oh, that's really great @viettrung9012 ! Thanks for spending your time on this. :slightly_smiling_face:

**Comment by viettrung9012** [comment]
@icyflame The PR is updated

**Comment by icyflame** [comment]
Hey @viettrung9012, code looks good. I will test it out a bit and then merge it into master. Thanks for the update! 😄

**Comment by icyflame** [comment]
I have merged this into master. I also added better reporting, a progress bar and some more fancy stuff! :smile:

**Pull request merged**
